services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: local
    volumes:
      - ./data/mongodb:/data/db
